language: python
python:
  - "2.7"
env:
  - DJANGO=1.4.13
  - DJANGO=1.5.8
  - DJANGO=1.6.5
install:
  - pip install -e .
  - pip install -q Django==$DJANGO flake8 coverage coveralls
before_script:
  - flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark notification
script:
  - coverage run runtests.py
after_script:
  - coveralls
